In [1]:
import numpy as np

In [2]:
## DataTypes & Attributes

In [69]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])

In [8]:
type(a1)

numpy.ndarray

In [70]:
a2 = np.array([[1,2,3.5], 
              [4,5,6.5]])

In [12]:
print(a2)

[[1.  2.  3.5]
 [4.  5.  6.5]]


In [13]:
a2.shape

(2, 3)

In [14]:
a1.shape

(3,)

In [15]:
a1.ndim, a2.ndim

(1, 2)

In [16]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [17]:
a1.size, a2.size

(3, 6)

In [18]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [19]:
#Create a dataframe from a Numpy array 
import pandas as pd 
df = pd.DataFrame(a1) 
df

0
0  1
1  2
2  3

In [2]:
**Creating arrays**

SyntaxError: invalid syntax (2833031934.py, line 1)

In [3]:
<strong>bold text</strong>

SyntaxError: invalid syntax (4286809447.py, line 1)

In [4]:
## **Creating arrays**

In [5]:
# **Creating arrays**

In [6]:
<h2><b>Creating arrays</b></h2>


SyntaxError: invalid syntax (222669451.py, line 1)

In [7]:
**this is a bold text** 

SyntaxError: invalid syntax (2034886092.py, line 1)

In [8]:
# for titles

In [9]:
## 2. Creating Arrays

In [11]:
sample_array = np.array([1,2,3])

NameError: name 'np' is not defined

In [13]:
import numpy as np

In [15]:
sample_array = np.array([1,2,3])

In [16]:
sample_array.shape

(3,)

In [17]:
sample_array.ndim

1

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
type(ones.ndarry)

AttributeError: 'numpy.ndarray' object has no attribute 'ndarry'

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [24]:
zeros = np.zeros(4)

In [25]:
zeros

array([0., 0., 0., 0.])

In [26]:
zeros = np.zeros((4,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0,10, size=(3,5))

In [32]:
random_array

array([[1, 2, 3, 2, 8],
       [8, 6, 7, 1, 5],
       [4, 7, 4, 2, 4]])

In [33]:
random_array = np.random.randint(0,3000, size = (500,500,500))

In [34]:
random_array

array([[[ 989,  573, 1409, ...,  861,  633, 2508],
        [2047,  688, 1923, ..., 2175, 1760, 2363],
        [ 185,  123, 1267, ...,  741,  248, 2247],
        ...,
        [1932, 1735,  111, ..., 1480, 2465, 1784],
        [  31,  943,   79, ..., 1618,  243, 1213],
        [ 104, 1034, 2438, ..., 1983, 1522, 2163]],

       [[1014,  492,  484, ...,  973, 1224, 1858],
        [ 672, 1087, 1762, ...,  192, 1357, 1534],
        [2463, 1269, 1873, ..., 2325, 1639, 1471],
        ...,
        [1317, 1557, 1441, ...,    9, 2787, 1206],
        [1607, 1805, 1048, ..., 2175,   49, 2982],
        [1255, 1212,  807, ..., 2582,  938, 1176]],

       [[ 577, 1694, 2037, ...,  280, 2454,  214],
        [2383, 1849, 1559, ...,  435, 1036, 1671],
        [2534, 2345,  968, ..., 1366, 1371,  490],
        ...,
        [ 404, 1043, 1976, ..., 2363, 1932,  303],
        [2571, 2194, 2963, ..., 2537, 1259, 2631],
        [ 469, 1421,  151, ..., 2675,  773,  721]],

       ...,

       [[ 988, 2452, 288

In [35]:
random_array.size

125000000

In [36]:
random_array.shape

(500, 500, 500)

In [37]:
np.random.random((5,3))

array([[0.50059626, 0.59763459, 0.7715873 ],
       [0.0687395 , 0.1127031 , 0.1061364 ],
       [0.88243949, 0.38195705, 0.95875479],
       [0.16989993, 0.15967266, 0.32599768],
       [0.5426758 , 0.06197605, 0.96081977]])

In [38]:
random_array_2 = np.random.rand(50,30)

In [39]:
random_array_2

array([[0.1075148 , 0.9163709 , 0.37075078, ..., 0.52285656, 0.36925246,
        0.66305933],
       [0.63515908, 0.2175274 , 0.61100632, ..., 0.67364291, 0.6740108 ,
        0.38306458],
       [0.80963577, 0.63530812, 0.79077815, ..., 0.20339672, 0.1627257 ,
        0.5876525 ],
       ...,
       [0.60003704, 0.62053707, 0.9208282 , ..., 0.00624297, 0.58873059,
        0.68201238],
       [0.73987883, 0.90533553, 0.99156538, ..., 0.29940258, 0.63271378,
        0.90970935],
       [0.87156272, 0.20799108, 0.99054535, ..., 0.04457142, 0.35333366,
        0.78153401]])

In [40]:
random_array_3 = np.random.rand(10,20,30)

In [41]:
random_array_3

array([[[0.49622052, 0.10870548, 0.86838157, ..., 0.39179796,
         0.35831922, 0.19552618],
        [0.50174236, 0.61743601, 0.65978581, ..., 0.90078321,
         0.87935455, 0.79857564],
        [0.56589795, 0.04217152, 0.21276949, ..., 0.09707326,
         0.26196259, 0.82713408],
        ...,
        [0.66187273, 0.19644285, 0.75772058, ..., 0.05805008,
         0.19968956, 0.60242096],
        [0.41331682, 0.87361517, 0.77107366, ..., 0.01205189,
         0.78533663, 0.46962953],
        [0.65085304, 0.60336452, 0.78332887, ..., 0.25827706,
         0.21995324, 0.83977354]],

       [[0.77070266, 0.66664588, 0.22281453, ..., 0.40232521,
         0.06183961, 0.34555271],
        [0.48694295, 0.03825634, 0.92970717, ..., 0.22745242,
         0.26007755, 0.81472578],
        [0.00114558, 0.27095106, 0.39278769, ..., 0.56537884,
         0.18072846, 0.08908746],
        ...,
        [0.55869386, 0.04042951, 0.17665775, ..., 0.7554226 ,
         0.17717622, 0.27449563],
        [0.3

In [42]:
# Pseudo-random numbers

In [43]:
np.random.seed()

In [62]:
np.random.seed(seed = 0)   
random_array_4 = np.random.randint(10, size=(5,3))     
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [63]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [65]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
random_array_4.shape

(5, 3)

In [66]:
## 3. Viewwing arrays and matrices 

In [67]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a1

NameError: name 'a1' is not defined

In [71]:
a1

array([1, 2, 3])

In [72]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [73]:
a1[0]

1

In [74]:
a2[0]

array([1. , 2. , 3.5])

In [75]:
a2.shape

(2, 3)

In [76]:
a2[1]

array([4. , 5. , 6.5])

In [77]:
a2 [:]

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [78]:
a2 [:2, :2, :2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [79]:
a2 [:2, :2]

array([[1., 2.],
       [4., 5.]])

In [80]:
## 4. Manipulating & comparing array

In [81]:
### Arithmetic 

In [82]:
ones = np.ones(3)

In [83]:
ones

array([1., 1., 1.])

In [84]:
a1 + ones

array([2., 3., 4.])

In [85]:
a1 - ones

array([0., 1., 2.])

In [86]:
a1 * ones

array([1., 2., 3.])

In [87]:
a1 * a2

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [88]:
a1 / ones

array([1., 2., 3.])

In [89]:
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [90]:
a2 ** a1

array([[  1.   ,   4.   ,  42.875],
       [  4.   ,  25.   , 274.625]])

In [91]:
a2 ** 2


array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 42.25]])

In [92]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [93]:
np.square(a2)

array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 42.25]])

In [94]:
np.add(a1, ones)

array([2., 3., 4.])

In [95]:
a1 % 2

array([1, 0, 1])

In [96]:
np.mod(a1, a2)

array([[0., 0., 3.],
       [1., 2., 3.]])

In [97]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [98]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [99]:
## Aggregation

In [100]:
listy_list = [1,2,3]

In [101]:
type(listy_list)

list

In [102]:
sum(listy_list)

6

In [103]:
a1

array([1, 2, 3])

In [104]:
sum(a1)

6

In [105]:
np.sum(a1)

6

In [106]:
massive_array = np.random.random(1000000000)

In [107]:
massive_array

array([0.79172504, 0.52889492, 0.56804456, ..., 0.87586069, 0.07715493,
       0.13286603])

In [108]:
massive_array[:100]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
       0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559,
       0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358,
       0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
       0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660

In [ ]:
%timeit sum(massive_array)

In [ ]:
%timeit np.sum(massive_array)

In [ ]:
%timeit np.sum(massive_array)

In [ ]:
%timeit sum(massive_array) 
%timeit np.sum(massive_array)

In [ ]:
print(%timeit np.sum(massive_array))

In [ ]:
np.mean(a2)

In [ ]:
np.std(a2)