In [1]:
import numpy as np

In [2]:
## DataTypes & Attributes

In [7]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])

In [8]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,3.5], 
              [4,5,6.5]])

In [12]:
print(a2)

[[1.  2.  3.5]
 [4.  5.  6.5]]


In [13]:
a2.shape

(2, 3)

In [14]:
a1.shape

(3,)

In [15]:
a1.ndim, a2.ndim

(1, 2)

In [16]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [17]:
a1.size, a2.size

(3, 6)

In [18]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [19]:
#Create a dataframe from a Numpy array 
import pandas as pd 
df = pd.DataFrame(a1) 
df

0
0  1
1  2
2  3

In [2]:
**Creating arrays**

SyntaxError: invalid syntax (2833031934.py, line 1)

In [3]:
<strong>bold text</strong>

SyntaxError: invalid syntax (4286809447.py, line 1)

In [4]:
## **Creating arrays**

In [5]:
# **Creating arrays**

In [6]:
<h2><b>Creating arrays</b></h2>


SyntaxError: invalid syntax (222669451.py, line 1)

In [7]:
**this is a bold text** 

SyntaxError: invalid syntax (2034886092.py, line 1)

In [8]:
# for titles

In [9]:
## 2. Creating Arrays

In [11]:
sample_array = np.array([1,2,3])

NameError: name 'np' is not defined

In [13]:
import numpy as np

In [15]:
sample_array = np.array([1,2,3])

In [16]:
sample_array.shape

(3,)

In [17]:
sample_array.ndim

1

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
type(ones.ndarry)

AttributeError: 'numpy.ndarray' object has no attribute 'ndarry'

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [24]:
zeros = np.zeros(4)

In [25]:
zeros

array([0., 0., 0., 0.])

In [26]:
zeros = np.zeros((4,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0,10, size=(3,5))

In [32]:
random_array

array([[1, 2, 3, 2, 8],
       [8, 6, 7, 1, 5],
       [4, 7, 4, 2, 4]])

In [33]:
random_array = np.random.randint(0,3000, size = (500,500,500))

In [34]:
random_array

array([[[ 989,  573, 1409, ...,  861,  633, 2508],
        [2047,  688, 1923, ..., 2175, 1760, 2363],
        [ 185,  123, 1267, ...,  741,  248, 2247],
        ...,
        [1932, 1735,  111, ..., 1480, 2465, 1784],
        [  31,  943,   79, ..., 1618,  243, 1213],
        [ 104, 1034, 2438, ..., 1983, 1522, 2163]],

       [[1014,  492,  484, ...,  973, 1224, 1858],
        [ 672, 1087, 1762, ...,  192, 1357, 1534],
        [2463, 1269, 1873, ..., 2325, 1639, 1471],
        ...,
        [1317, 1557, 1441, ...,    9, 2787, 1206],
        [1607, 1805, 1048, ..., 2175,   49, 2982],
        [1255, 1212,  807, ..., 2582,  938, 1176]],

       [[ 577, 1694, 2037, ...,  280, 2454,  214],
        [2383, 1849, 1559, ...,  435, 1036, 1671],
        [2534, 2345,  968, ..., 1366, 1371,  490],
        ...,
        [ 404, 1043, 1976, ..., 2363, 1932,  303],
        [2571, 2194, 2963, ..., 2537, 1259, 2631],
        [ 469, 1421,  151, ..., 2675,  773,  721]],

       ...,

       [[ 988, 2452, 288

In [35]:
random_array.size

125000000

In [36]:
random_array.shape

(500, 500, 500)

In [37]:
np.random.random((5,3))

array([[0.50059626, 0.59763459, 0.7715873 ],
       [0.0687395 , 0.1127031 , 0.1061364 ],
       [0.88243949, 0.38195705, 0.95875479],
       [0.16989993, 0.15967266, 0.32599768],
       [0.5426758 , 0.06197605, 0.96081977]])

In [38]:
random_array_2 = np.random.rand(50,30)

In [39]:
random_array_2

array([[0.1075148 , 0.9163709 , 0.37075078, ..., 0.52285656, 0.36925246,
        0.66305933],
       [0.63515908, 0.2175274 , 0.61100632, ..., 0.67364291, 0.6740108 ,
        0.38306458],
       [0.80963577, 0.63530812, 0.79077815, ..., 0.20339672, 0.1627257 ,
        0.5876525 ],
       ...,
       [0.60003704, 0.62053707, 0.9208282 , ..., 0.00624297, 0.58873059,
        0.68201238],
       [0.73987883, 0.90533553, 0.99156538, ..., 0.29940258, 0.63271378,
        0.90970935],
       [0.87156272, 0.20799108, 0.99054535, ..., 0.04457142, 0.35333366,
        0.78153401]])

In [ ]:
random_array_3 = np.random.rand(10,20)