In [1]:
import numpy as np

In [2]:
## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.5], 
              [4,5,6.5]])

In [6]:
print(a2)

[[1.  2.  3.5]
 [4.  5.  6.5]]


In [7]:
a2.shape

(2, 3)

In [8]:
a1.shape

(3,)

In [9]:
a1.ndim, a2.ndim

(1, 2)

In [10]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [11]:
a1.size, a2.size

(3, 6)

In [12]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [13]:
#Create a dataframe from a Numpy array 
import pandas as pd 
df = pd.DataFrame(a1) 
df

0
0  1
1  2
2  3

In [14]:
**Creating arrays**

SyntaxError: invalid syntax (2833031934.py, line 1)

In [ ]:
<strong>bold text</strong>

In [ ]:
## **Creating arrays**

In [ ]:
# **Creating arrays**

In [ ]:
<h2><b>Creating arrays</b></h2>


In [ ]:
**this is a bold text** 

In [ ]:
# for titles

In [ ]:
## 2. Creating Arrays

In [15]:
sample_array = np.array([1,2,3])

In [16]:
import numpy as np

In [17]:
sample_array = np.array([1,2,3])

In [18]:
sample_array.shape

(3,)

In [19]:
sample_array.ndim

1

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
type(ones.ndarry)

AttributeError: 'numpy.ndarray' object has no attribute 'ndarry'

In [ ]:
type(ones)

In [24]:
zeros = np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [25]:
zeros = np.zeros(4)

In [26]:
zeros

array([0., 0., 0., 0.])

In [27]:
zeros = np.zeros((4,5))

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10, size=(3,5))

In [31]:
random_array

array([[9, 3, 0, 7, 3],
       [4, 1, 0, 3, 8],
       [9, 9, 3, 7, 9]])

In [32]:
random_array = np.random.randint(0,3000, size = (500,500,500))

In [33]:
random_array

array([[[ 584,  751, 2979, ...,  768, 2714,  107],
        [ 102, 1902, 1138, ..., 1439, 1632, 2888],
        [1424, 1423,  223, ..., 1261, 2945,   17],
        ...,
        [1265,  217,  773, ..., 2284, 2910, 2298],
        [ 411, 2465,  665, ..., 1928,  686, 1313],
        [2507, 1012, 2017, ..., 2308,  145, 2995]],

       [[2412,  181, 2628, ...,  839, 1686, 1461],
        [ 139, 1632, 1949, ..., 2291,  715, 2097],
        [2443, 1179, 1413, ..., 2704, 2715,    0],
        ...,
        [1511, 2478, 1619, ..., 2993, 2227,  586],
        [2572,  371, 2450, ...,  664, 2569,  143],
        [1471, 1455, 1749, ..., 2080, 1226, 2480]],

       [[ 771, 2724,  759, ...,  858, 1447, 1805],
        [ 763, 1592,  529, ...,  409,   68,   16],
        [2806, 2607, 2541, ..., 1749,  421, 2316],
        ...,
        [1436, 1925, 1997, ..., 2992, 2247,  460],
        [1515,  376, 1379, ..., 1054, 1039, 1396],
        [2683, 2928, 1365, ...,  634, 2576, 2205]],

       ...,

       [[2508, 2769, 239

In [34]:
random_array.size

125000000

In [35]:
random_array.shape

(500, 500, 500)

In [36]:
np.random.random((5,3))

array([[0.91507877, 0.77545074, 0.79568233],
       [0.61101815, 0.62391277, 0.6631369 ],
       [0.13002695, 0.53640314, 0.72256983],
       [0.23333732, 0.9505642 , 0.57206434],
       [0.2912477 , 0.36169469, 0.92248222]])

In [37]:
random_array_2 = np.random.rand(50,30)

In [38]:
random_array_2

array([[0.04062395, 0.52428393, 0.01265448, ..., 0.84740233, 0.06967148,
        0.82670302],
       [0.37678334, 0.45048061, 0.35046765, ..., 0.61148118, 0.76092973,
        0.48089394],
       [0.88861223, 0.69713126, 0.00700534, ..., 0.50415311, 0.44225025,
        0.50721032],
       ...,
       [0.12525364, 0.29385722, 0.03770341, ..., 0.2613761 , 0.59235636,
        0.46724465],
       [0.18716425, 0.30067674, 0.78611444, ..., 0.32862521, 0.5290642 ,
        0.77334809],
       [0.62658826, 0.16224739, 0.17646633, ..., 0.01353477, 0.2754105 ,
        0.3608639 ]])

In [39]:
random_array_3 = np.random.rand(10,20,30)

In [40]:
random_array_3

array([[[0.35331056, 0.37839094, 0.8427823 , ..., 0.25600147,
         0.03540586, 0.28787882],
        [0.37185887, 0.91637541, 0.0844761 , ..., 0.57764282,
         0.82714777, 0.1383003 ],
        [0.79091193, 0.13588688, 0.65439918, ..., 0.42550951,
         0.65146978, 0.95832132],
        ...,
        [0.35151235, 0.54135809, 0.92406521, ..., 0.0628391 ,
         0.73172091, 0.46475047],
        [0.17646984, 0.96863004, 0.00970532, ..., 0.77216551,
         0.80300681, 0.85772166],
        [0.8399657 , 0.90275158, 0.23745704, ..., 0.36793525,
         0.0897505 , 0.66986124]],

       [[0.12202817, 0.87031088, 0.95443488, ..., 0.34076705,
         0.48722117, 0.82449443],
        [0.62790472, 0.16303908, 0.42515684, ..., 0.14401558,
         0.35615152, 0.25975676],
        [0.45028116, 0.61873795, 0.62465077, ..., 0.46978718,
         0.82325492, 0.99959018],
        ...,
        [0.23818892, 0.15904488, 0.5566372 , ..., 0.68902039,
         0.2448    , 0.40002832],
        [0.1

In [41]:
# Pseudo-random numbers

In [42]:
np.random.seed()

In [43]:
np.random.seed(seed = 0)   
random_array_4 = np.random.randint(10, size=(5,3))     
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [44]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [45]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [47]:
random_array_4.shape

(5, 3)

In [48]:
## 3. Viewwing arrays and matrices 

In [49]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1

array([1, 2, 3])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [53]:
a1[0]

1

In [54]:
a2[0]

array([1. , 2. , 3.5])

In [55]:
a2.shape

(2, 3)

In [56]:
a2[1]

array([4. , 5. , 6.5])

In [57]:
a2 [:]

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [58]:
a2 [:2, :2, :2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [59]:
a2 [:2, :2]

array([[1., 2.],
       [4., 5.]])

In [60]:
## 4. Manipulating & comparing array

In [61]:
### Arithmetic 

In [62]:
ones = np.ones(3)

In [63]:
ones

array([1., 1., 1.])

In [64]:
a1 + ones

array([2., 3., 4.])

In [65]:
a1 - ones

array([0., 1., 2.])

In [66]:
a1 * ones

array([1., 2., 3.])

In [67]:
a1 * a2

array([[ 1. ,  4. , 10.5],
       [ 4. , 10. , 19.5]])

In [68]:
a1 / ones

array([1., 2., 3.])

In [69]:
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [70]:
a2 ** a1

array([[  1.   ,   4.   ,  42.875],
       [  4.   ,  25.   , 274.625]])

In [71]:
a2 ** 2


array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 42.25]])

In [72]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [73]:
np.square(a2)

array([[ 1.  ,  4.  , 12.25],
       [16.  , 25.  , 42.25]])

In [74]:
np.add(a1, ones)

array([2., 3., 4.])

In [75]:
a1 % 2

array([1, 0, 1])

In [76]:
np.mod(a1, a2)

array([[0., 0., 3.],
       [1., 2., 3.]])

In [77]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [78]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [79]:
## Aggregation

In [80]:
listy_list = [1,2,3]

In [81]:
type(listy_list)

list

In [82]:
sum(listy_list)

6

In [83]:
a1

array([1, 2, 3])

In [84]:
sum(a1)

6

In [85]:
np.sum(a1)

6

In [86]:
massive_array = np.random.random(1000000000)

In [87]:
massive_array

array([0.79172504, 0.52889492, 0.56804456, ..., 0.87586069, 0.07715493,
       0.13286603])

In [88]:
massive_array[:100]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
       0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559,
       0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358,
       0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
       0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660

In [ ]:
%timeit sum(massive_array)

In [ ]:
%timeit np.sum(massive_array)

In [ ]:
%timeit np.sum(massive_array)

In [ ]:
%timeit sum(massive_array) 
%timeit np.sum(massive_array)

In [ ]:
%timeit np.sum(massive_array)

In [ ]:
np.mean(a2)

In [ ]:
np.std(a2)